export const SEARCHC_SUCCESS = "SEARCHC_SUCCESS";
export const SEARCHC_START = "SEARCHC_START";
export const SEARCHC_FIELD = "SEARCHC_FIELD";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_START = "ADD_COMMENT_START";
export const ADD_COMMENT_FIELD = "ADD_COMMENT_FIELD";

export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS";
export const ADD_LIKE_START = "ADD_LIKE_START";
export const ADD_LIKE_FIELD = "ADD_LIKE_FIELD";

export const UN_LIKE_SUCCESS = "UN_LIKE_SUCCESS";
export const UN_LIKE_START = "UN_LIKE_START";
export const UN_LIKE_FIELD = "UN_LIKE_FIELD";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_START = "CREATE_POST_START";
export const CREATE_POST_FIELD = "CREATE_POST_FIELD";

export const UPDTE_POST_SUCCESS = "UPDTE_POST_SUCCESS";

export const GET_MY_POST_SUCCESS = "GET_MY_POST_SUCCESS";
export const GET_MY_POST_START = "GET_MY_POST_START";
export const GET_MY_POST_FIELD = "GET_MY_POST_FIELD";

export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_START = "GET_POST_START";
export const GET_POST_FIELD = "GET_POST_FIELD";