
export const GET_MY_CHATS_SUCCESS = "GET_MY_CHATS_SUCCESS";
export const GET_MY_CHATS_START = "GET_MY_CHATS_START";
export const GET_MY_CHATS_FIELD = "GET_MY_CHATS_FIELD";

export const GET_USER_CHAT_SUCCESS = "GET_USER_CHAT_SUCCESS";
export const GET_USER_CHAT_START = "GET_USER_CHAT_START";
export const GET_USER_CHAT_FIELD = "GET_USER_CHAT_FIELD";

export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_START = "SEND_MESSAGE_START";
export const SEND_MESSAGE_FIELD = "SEND_MESSAGE_FIELD";
export const UPDATE_MESSAGES_SUCCESS = "UPDATE_MESSAGES_SUCCESS";

export const UPDATE_RESEVER_SUCCESS = "UPDATE_RESEVER_SUCCESS";

