
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_START = "GET_NOTIFICATIONS_START";
export const GET_NOTIFICATIONS_FIELD = "GET_NOTIFICATIONS_FIELD";

export const CLICK_NOTIFICATION_SUCCESS = "CLICK_NOTIFICATION_SUCCESS";
export const CLICK_NOTIFICATION_START = "CLICK_NOTIFICATION_START";
export const CLICK_NOTIFICATION_FIELD = "CLICK_NOTIFICATION_FIELD";

