

export const LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const LOGOUT_START = "USER_LOGOUT_START";
export const LOGOUT_FIELD = "USER_LOGOUT_FIELD";

export const LOGIN_START = "USER_LOGIN_START";
export const LOGIN_FIALD = "USER_LOGIN_FIALD";
export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const REST_START = "USER_RESET_START";
export const REST_FIALD = "USER_RESET_FIALD";
export const REST_SUCCESS = "USER_RESET_SUCCESS";

export const REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const REGISTER_START = "USER_REGISTER_START";
export const REGISTER_FIALD = "USER_REGISTER_FIALD";

export const GET_USER_START = "GET_USER_START";
export const GET_USER_FIALD = "GET_USER_FIALD";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const UPDATE_START = "UPDATE_START";
export const UPDATE_FIALD = "UPDATE_FIALD";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
