
export const GET_MY_FOLLOWERS_SUCCESS = "GET_MY_FOLLOWERS_SUCCESS";
export const GET_MY_FOLLOWERS_START = "GET_MY_FOLLOWERS_START";
export const GET_MY_FOLLOWERS_FIELD = "GET_MY_FOLLOWERS_FIELD";

export const GET_FOLLOW_THEIR_SUCCESS = "GET_FOLLOW_THEIR_SUCCESS";
export const GET_FOLLOW_THEIR_START = "GET_FOLLOW_THEIR_START";
export const GET_FOLLOW_THEIR_FIELD = "GET_FOLLOW_THEIR_FIELD";


export const GET_ADD_FOLLOW_SUCCESS = "GET_ADD_FOLLOW_SUCCESS";
export const GET_ADD_FOLLOW_START = "GET_ADD_FOLLOW_START";
export const GET_ADD_FOLLOW_FIELD = "GET_ADD_FOLLOW_FIELD";

export const UN_FOLLOW_SUCCESS = "UN_FOLLOW_SUCCESS";
export const UN_FOLLOW_START = "UN_FOLLOW_START";
export const UN_FOLLOW_FIELD = "UN_FOLLOW_FIELD";